.\" Manpage for Hangman in Bash.
.TH man 6 "3 April 2017" "1.0" "Hangman for Bash"
.SH NAME
hangman \- play Hangman in your Bash shell! 
.SH SYNOPSIS
hangman [-d] [-w]
.SH DESCRIPTION
Hangman in bash!
.SH OPTIONS
Hangman takes -w and -d options. 

-w for your own word (cheat mode)

-d for your own dictionary file.

.SH BUGS
No known bugs.
.SH AUTHORS
Mitch Terpak

Pim Merks
